#!/bin/bash
HASH='%C(bold blue)%h%C(reset)'
DATE='%C(bold cyan)%aD%C(reset)'
RELATIVE_TIME='%C(bold green)(%ar)%C(reset)'
REFS='%C(bold yellow)%d%C(reset)'
COMMIT_MSG='%C(white)%s%C(reset)'
AUTHOR='%C(dim white)- %an%C(reset)'

FORMAT="${HASH} - ${DATE} ${RELATIVE_TIME}${REFS}%n    ${COMMIT_MSG} ${AUTHOR}"

git_branch_log() {
	git log --graph --abbrev-commit --decorate --pretty="tformat:${FORMAT}"
}

git_complete_log() {
	git log --graph --abbrev-commit --decorate --all --pretty="tformat:${FORMAT}"
}

