#!/usr/bin/env bash

# Install Monaco font for Linux
if [ "$(uname)" == "Linux" ]; then
	sudo mkdir -p /usr/share/fonts/truetype/custom
	sudo cp Monaco_Linux.ttf /usr/share/fonts/truetype/custom/
	sudo fc-cache -f -v
fi

cat <<EOT >> ~/.profile
if [ -f ~/.terminal/shell_config.sh ]; then
	. ~/.terminal/shell_config.sh
fi
EOT

cat <<EOT >> ~/.gitconfig
[alias]
	sl = "!bash -c 'source ~/.terminal/gitlog && git_branch_log'"
	l = "!bash -c 'source ~/.terminal/gitlog && git_complete_log'"
[gui]
	encoding = utf-8
[i18n]
	commitencoding = utf-8
[core]
	editor = vim
[color]
	diff = auto
[diff]
	tool = vimdiff
[difftool]
	prompt = false
EOT

# setup vim setting
ln -s ~/.terminal/vim ~/.vim
ln -s ~/.terminal/vim/vimrc ~/.vimrc


exit 0
