#!/usr/bin/env bash

# Install Monaco font for Linux
if [ "$(uname)" == "Linux" ]; then
	sudo mkdir -p /usr/share/fonts/truetype/custom
	sudo cp Monaco_Linux.ttf /usr/share/fonts/truetype/custom/
	sudo fc-cache -f -v
fi

cat <<EOT >> ~/.bashrc
if [ -f ~/.dotfiles/bash_custom ]; then
	. ~/.dotfiles/bash_custom
fi
EOT

cat <<EOT >> ~/.gitconfig
[alias]
	sl = "!bash -c 'source ~/.dotfiles/gitlog && git_branch_log'"
	l = "!bash -c 'source ~/.dotfiles/gitlog && git_complete_log'"
[gui]
	encoding = utf-8
[i18n]
	commitencoding = utf-8
[core]
	editor = vim
[color]
	diff = auto
[diff]
	tool = vimdiff
[difftool]
	prompt = false
EOT


exit 0
